export const scenarios={
 linked:{label:"Linked · writes paused",badge:"Linked",tone:"good",payload:"Available",permission:"Write",userGate:"Paused",deploymentGate:"Enabled",external:"Not requested",title:"Linked. Writes stay paused.",copy:"Your connection is ready. Linking or replacing credentials never resumes background writes automatically.",action:"Resume writes only after reviewing the current gate and connection.",connect:"Replace connection",canConnect:true,canDisconnect:true,canResume:true},
 active:{label:"Linked · writes enabled",badge:"Linked",tone:"good",payload:"Available",permission:"Write",userGate:"Enabled",deploymentGate:"Enabled",external:"Not requested",title:"Connection ready",copy:"The connection and write gates allow ordinary operations. Existing submission safety rules still apply.",action:"Replacing or disconnecting the connection pauses new operations.",connect:"Replace connection",canConnect:true,canDisconnect:true,canResume:false},
 replacing:{label:"Credential replacement",badge:"Replacing",tone:"warn",payload:"Replacement pending",permission:"Last verified: Write",userGate:"Paused",deploymentGate:"Enabled",external:"Not requested",title:"Updating the connection",copy:"New Flickr operations are paused while the new credentials are verified. Queued work is retained.",action:"Wait for this operation to settle before starting another replacement or disconnect.",connect:"Replacement in progress",canConnect:false,canDisconnect:false,canResume:false},
 repair_required:{label:"Repair required",badge:"Needs repair",tone:"bad",payload:"Unconfirmed",permission:"Not current authority",userGate:"Paused",deploymentGate:"Enabled",external:"Not requested",title:"The connection needs repair",copy:"The previous credential change could not be confirmed. New operations remain stopped; an uncertain update is never blindly repeated.",action:"Check the operation outcome before relinking. A timeout alone does not make a replacement safe.",connect:"Review repair steps",canConnect:true,canDisconnect:false,canResume:false},
 disconnecting:{label:"Disconnecting",badge:"Disconnecting",tone:"warn",payload:"Retirement pending",permission:"Not usable",userGate:"Paused",deploymentGate:"Enabled",external:"Owner action required",title:"Stopped locally. Cleanup is pending.",copy:"No new authenticated Flickr operation can start. The old credential payload is not yet confirmed retired.",action:"Keep the connection stopped while cleanup is reconciled. Already-dispatched work cannot be recalled.",connect:"Cleanup in progress",canConnect:false,canDisconnect:false,canResume:false},
 relink_required:{label:"Flickr grant rejected",badge:"Relink required",tone:"warn",payload:"Stored but not usable",permission:"No longer current",userGate:"Paused",deploymentGate:"Enabled",external:"Not requested",title:"Flickr authorization needs renewal",copy:"Flickr definitively rejected the current grant. New operations remain stopped until a new grant is verified.",action:"Relink the same configured account. Existing queue and permanent blocks remain unchanged.",connect:"Link Flickr again",canConnect:true,canDisconnect:true,canResume:false},
 disconnected:{label:"Disconnected",badge:"Disconnected",tone:"",payload:"Retired",permission:"None active",userGate:"Paused",deploymentGate:"Enabled",external:"Owner action required",title:"Disconnected locally",copy:"The credential payload is retired and new operations are stopped. Remove the app permission in Flickr's account settings to finish the Flickr-side step.",action:"Local retirement is separate from Flickr permission removal. No provider-wide erasure is claimed.",connect:"Link Flickr again",canConnect:true,canDisconnect:false,canResume:false},
 unlinked:{label:"Not linked",badge:"Not linked",tone:"",payload:"None",permission:"Not verified",userGate:"Paused",deploymentGate:"Enabled",external:"Not requested",title:"Link your Flickr account",copy:"Link the configured account and grant write permission. Its owner and permission will be checked before it becomes active.",action:"You will continue to Flickr to authorize the connection. Writes remain paused afterward.",connect:"Link Flickr",canConnect:true,canDisconnect:false,canResume:false}
};
export function authorizationTarget(value){
 if(typeof value!=="string"||value.length>2048||/[\u0000-\u0020\u007f]/.test(value))throw new Error("Invalid authorization target");
 const url=new URL(value),keys=[...url.searchParams.keys()];
 if(url.protocol!=="https:"||url.hostname!=="www.flickr.com"||url.port||url.username||url.password||url.hash||url.pathname!=="/services/oauth/authorize"||keys.length!==1||keys[0]!=="oauth_token"||!url.searchParams.get("oauth_token"))throw new Error("Invalid authorization target");
 return url.href;
}
