import test from "node:test";
import assert from "node:assert/strict";
import {sqlStore} from "./sql_store.mjs";
import {sourceKey,admitAuthentication,finishAuthentication} from "../src/auth_admission.ts";
import {startLogin,finishLogin,digest,authenticateBrowser,enforceUnsafe,logoutBrowser} from "../src/browser_sessions.ts";
import {beginLifecycle,dispatchLifecycle,reconcileLifecycle,connectionView} from "../src/native_lifecycle.ts";
function seeded(){const db=sqlStore();db.raw.exec("INSERT INTO fga_users VALUES('u');INSERT INTO flickr_links VALUES('u','owner',1,'linked');INSERT INTO flickr_native_credentials VALUES('u','old',1,'owner','write',NULL);INSERT INTO flickr_connection_state VALUES('u','linked','available','write',1000000,0,NULL);INSERT INTO flickr_write_gates VALUES('user','u',1,1),('deployment','*',1,1)");return db;}
const peer=async()=>Response.json({stat:"ok",oauth:{token:{_content:"t"},perms:{_content:"write"},user:{nsid:"owner"}}});
test("native lifecycle pauses, dispatches once, reconciles and leaves gates paused",async()=>{const db=seeded();let value="",calls=0;const op=await beginLifecycle(db,"u",1,"replace");assert.equal((await connectionView(db,"u")).state,"replacing");const writer={replace:async v=>{calls++;value=v;}};assert.equal(await dispatchLifecycle(db,op.operationId,writer,{token:"t",tokenSecret:"s"}),true);assert.equal(await dispatchLifecycle(db,op.operationId,writer,{token:"t",tokenSecret:"s"}),false);assert.equal(calls,1);const secrets={FLICKR_GRANT:{get:async()=>value},FLICKR_APPLICATION:{get:async()=>JSON.stringify({schemaVersion:1,consumerKey:"k",consumerSecret:"s"})}};assert.equal(await reconcileLifecycle(db,op.operationId,secrets,peer),true);const view=await connectionView(db,"u");assert.equal(view.state,"linked");assert.equal(view.revision,3);assert.equal(view.userWriteGate.state,"paused");assert.equal(await reconcileLifecycle(db,op.operationId,secrets,peer),false);db.raw.close();});
test("lost mutation acknowledgement retains ownership and matching generation repairs",async()=>{const db=seeded();const op=await beginLifecycle(db,"u",1,"retire");let value;await dispatchLifecycle(db,op.operationId,{replace:async v=>{value=v;throw new Error("lost");}});assert.equal((await connectionView(db,"u")).state,"repair_required");await assert.rejects(beginLifecycle(db,"u",2,"replace"));assert.equal(await dispatchLifecycle(db,op.operationId,{replace:async()=>assert.fail("must not retry")}),false);assert.equal(await reconcileLifecycle(db,op.operationId,{FLICKR_GRANT:{get:async()=>JSON.stringify({schemaVersion:1,generation:"wrong",retired:true})}},peer),false);assert.equal(await reconcileLifecycle(db,op.operationId,{FLICKR_GRANT:{get:async()=>value}},peer),true);assert.equal((await connectionView(db,"u")).localCredentialState,"retired");db.raw.close();});
test("lifecycle audit failure rolls back every authority change",async()=>{for(let fault=0;fault<8;fault++){const db=seeded();db.fault=fault;await assert.rejects(beginLifecycle(db,"u",1,"replace"));assert.equal(db.raw.prepare("SELECT state FROM flickr_links").get().state,"linked");assert.equal(db.raw.prepare("SELECT COUNT(*) n FROM flickr_lifecycle_operations").get().n,0);db.raw.close();}});
test("source normalization and shared quota reject excess before identity work",async()=>{assert.equal(sourceKey("2001:db8:abcd:1::1","s".repeat(32)),sourceKey("2001:db8:abcd:1::999","s".repeat(32)));assert.equal(sourceKey("::ffff:192.0.2.1","s".repeat(32)),sourceKey("192.0.2.1","s".repeat(32)));const db=sqlStore(),key="a".repeat(64);await admitAuthentication(db,key,"login");await admitAuthentication(db,key,"login");await assert.rejects(admitAuthentication(db,key,"login"),/rate_limited/);assert.equal(db.raw.prepare("SELECT COUNT(*) n FROM auth_cost_events").get().n,2);db.raw.close();});
test("invalid in-flight callback budget is charged before validation",async()=>{const db=sqlStore(),key="b".repeat(64);const ids=[];for(let i=0;i<20;i++)ids.push(await admitAuthentication(db,key,"callback"));await assert.rejects(admitAuthentication(db,key,"callback"),/rate_limited/);await finishAuthentication(db,ids[0]);await admitAuthentication(db,key,"callback");db.raw.close();});
async function login(db){const input=await startLogin(db);const cookie=await finishLogin(db,{stateDigest:digest(input.state),nonceDigest:digest(input.nonce),googleSub:"subject",ownerSub:"subject"});return {input,cookie:cookie.split(";")[0],setCookie:cookie};}
test("opaque sessions commit once and enforce cookie, owner, origin, CSRF and expiry",async()=>{const db=sqlStore();const {input,cookie,setCookie}=await login(db);assert.match(setCookie,/^__Host-fga_admin=[A-Za-z0-9_-]{43};/);for(const attribute of ["Path=/","Secure","HttpOnly","SameSite=Strict","Max-Age=86400"])assert(setCookie.includes(attribute));assert(!setCookie.includes("Domain="));await assert.rejects(finishLogin(db,{stateDigest:digest(input.state),nonceDigest:digest(input.nonce),googleSub:"subject",ownerSub:"subject"}));const req=new Request("https://flickrgroupaddr.com/api/v001/admin/session",{headers:{Cookie:cookie}});const session=await authenticateBrowser(req,db,"subject");await assert.rejects(authenticateBrowser(req,db,"removed"));const unsafe=new Request(req,{method:"POST",headers:{Cookie:cookie,Origin:"https://flickrgroupaddr.com","X-CSRF-Token":session.csrfToken}});enforceUnsafe(unsafe,session,true);assert.throws(()=>enforceUnsafe(new Request(req,{method:"POST"}),session));assert.throws(()=>enforceUnsafe(unsafe,{...session,nowUs:session.recentAtUs+300000001},true));enforceUnsafe(unsafe,{...session,nowUs:session.recentAtUs+300000000},true);const expired=await logoutBrowser(unsafe,db,"subject");assert(expired.includes("Max-Age=0"));await assert.rejects(authenticateBrowser(req,db,"subject"));db.raw.close();});
test("reauthentication rotates only the bound session and its CSRF",async()=>{const db=sqlStore();const one=await login(db),two=await login(db);const req=new Request("https://flickrgroupaddr.com/",{headers:{Cookie:one.cookie}});const bound=await authenticateBrowser(req,db,"subject");const tx=await startLogin(db,bound);const replacement=await finishLogin(db,{stateDigest:digest(tx.state),nonceDigest:digest(tx.nonce),googleSub:"subject",ownerSub:"subject"});await assert.rejects(authenticateBrowser(req,db,"subject"));await authenticateBrowser(new Request(req,{headers:{Cookie:two.cookie}}),db,"subject");const fresh=await authenticateBrowser(new Request(req,{headers:{Cookie:replacement.split(";")[0]}}),db,"subject");assert.notEqual(bound.csrfToken,fresh.csrfToken);db.raw.close();});
test("login audit fault preserves unconsumed transaction and creates no session",async()=>{const db=sqlStore();const input=await startLogin(db);db.fault=11;await assert.rejects(finishLogin(db,{stateDigest:digest(input.state),nonceDigest:digest(input.nonce),googleSub:"subject",ownerSub:"subject"}));assert.equal(db.raw.prepare("SELECT COUNT(*) n FROM admin_sessions").get().n,0);assert.equal(db.raw.prepare("SELECT consumed_at_us FROM google_login_transactions").get().consumed_at_us,null);db.raw.close();});

test("logout retries converge for revoked, absent and malformed cookies without an oracle",async()=>{const db=sqlStore();const {cookie}=await login(db);const req=new Request("https://flickrgroupaddr.com/",{headers:{Cookie:cookie}}),session=await authenticateBrowser(req,db,"subject");const unsafe=new Request(req,{method:"POST",headers:{Cookie:cookie,Origin:"https://flickrgroupaddr.com","X-CSRF-Token":session.csrfToken}});const first=await logoutBrowser(unsafe,db,"subject"),again=await logoutBrowser(unsafe,db,"subject");assert.equal(first,again);assert(first.includes("Expires=Thu, 01 Jan 1970"));for(const cookie of ["","__Host-fga_admin=bad","__Host-fga_admin="+"A".repeat(43)])assert.equal(await logoutBrowser(new Request(req,{method:"POST",headers:{Origin:"https://flickrgroupaddr.com",Cookie:cookie}}),db,"subject"),first);assert.equal(db.raw.prepare("SELECT COUNT(*) n FROM audit_events WHERE action='authentication.logout_succeeded'").get().n,1);db.raw.close();});
test("logout origin CSRF and audit failure preserve active authority",async()=>{const db=sqlStore();const {cookie}=await login(db);const req=new Request("https://flickrgroupaddr.com/",{headers:{Cookie:cookie}}),session=await authenticateBrowser(req,db,"subject");await assert.rejects(logoutBrowser(new Request(req,{method:"POST"}),db,"subject"),/invalid_origin/);await assert.rejects(logoutBrowser(new Request(req,{method:"POST",headers:{Cookie:cookie,Origin:"https://flickrgroupaddr.com"}}),db,"subject"),/invalid_csrf/);db.fault=2;await assert.rejects(logoutBrowser(new Request(req,{method:"POST",headers:{Cookie:cookie,Origin:"https://flickrgroupaddr.com","X-CSRF-Token":session.csrfToken}}),db,"subject"),/logout_outcome_unknown/);await authenticateBrowser(req,db,"subject");db.raw.close();});

test("definitive grant rejection retires the matching native payload and preserves relink required",async()=>{const {verifyPhoto}=await import("../src/flickr_reads.ts");const db=seeded(),hash="a".repeat(64);db.raw.exec("BEGIN;INSERT INTO installations(installation_id,user_id,credential_class,state,revision,current_version_id) VALUES('i','u','lrc_plugin','active',1,'v');INSERT INTO installation_credential_versions(version_id,installation_id,credential_digest,state,ordinal) VALUES('v','i','"+hash+"','current',1);COMMIT");let value=JSON.stringify({schemaVersion:1,generation:"old",token:"t",tokenSecret:"s"});const secrets={FLICKR_GRANT:{get:async()=>value},FLICKR_APPLICATION:{get:async()=>JSON.stringify({schemaVersion:1,consumerKey:"k",consumerSecret:"s"})}};await assert.rejects(verifyPhoto(db,{installationId:"i",credentialDigest:hash},secrets,{userId:"u",ownerNsid:"owner",revision:"1",generation:"old"},"photo",async()=>Response.json({stat:"fail",code:98})),/flickr_link_changed/);const op=db.raw.prepare("SELECT operation_id FROM flickr_lifecycle_operations").get();assert.equal((await connectionView(db,"u")).state,"relink_required");await dispatchLifecycle(db,op.operation_id,{replace:async raw=>{value=raw;}});assert.equal(await reconcileLifecycle(db,op.operation_id,secrets,peer),true);const view=await connectionView(db,"u");assert.equal(view.state,"relink_required");assert.equal(view.localCredentialState,"retired");assert.equal(view.fgaOperationState,"stopped");assert.equal(db.raw.prepare("SELECT COUNT(*) n FROM flickr_native_credentials").get().n,0);db.raw.close();});
test("stale grant rejection cannot disable a newer native generation",async()=>{const {verifyPhoto}=await import("../src/flickr_reads.ts");const db=seeded(),hash="a".repeat(64);db.raw.exec("BEGIN;INSERT INTO installations(installation_id,user_id,credential_class,state,revision,current_version_id) VALUES('i','u','lrc_plugin','active',1,'v');INSERT INTO installation_credential_versions(version_id,installation_id,credential_digest,state,ordinal) VALUES('v','i','"+hash+"','current',1);COMMIT");const secrets={FLICKR_GRANT:{get:async()=>JSON.stringify({schemaVersion:1,generation:"old",token:"t",tokenSecret:"s"})},FLICKR_APPLICATION:{get:async()=>JSON.stringify({schemaVersion:1,consumerKey:"k",consumerSecret:"s"})}};await assert.rejects(verifyPhoto(db,{installationId:"i",credentialDigest:hash},secrets,{userId:"u",ownerNsid:"owner",revision:"1",generation:"old"},"photo",async()=>{db.raw.exec("UPDATE flickr_links SET link_revision=2;UPDATE flickr_native_credentials SET active_generation='successor',link_revision=2");return Response.json({stat:"fail",code:99});}));assert.equal(db.raw.prepare("SELECT state FROM flickr_links").get().state,"linked");assert.equal(db.raw.prepare("SELECT active_generation FROM flickr_native_credentials").get().active_generation,"successor");assert.equal(db.raw.prepare("SELECT COUNT(*) n FROM flickr_lifecycle_operations").get().n,0);db.raw.close();});

test("first owner login initializes an unlinked connection with both gates paused",async()=>{const db=sqlStore(),tx=await startLogin(db);await finishLogin(db,{stateDigest:digest(tx.state),nonceDigest:digest(tx.nonce),googleSub:"subject",ownerSub:"subject",ownerNsid:"123456789@N00"});const user=db.raw.prepare("SELECT user_id FROM admin_principals").get().user_id;const view=await connectionView(db,user);assert.equal(view.state,"unlinked");assert.equal(view.flickrOwnerNsid,"123456789@N00");assert.equal(view.userWriteGate.state,"paused");assert.equal(view.deploymentWriteGate.state,"paused");db.raw.close();});

test("similarly named cookies cannot shadow the exact administrative cookie",async()=>{const db=sqlStore(),current=await login(db);const request=new Request("https://flickrgroupaddr.com/",{headers:{Cookie:current.cookie+"; __Host_fga_admin="+"A".repeat(43)}});const session=await authenticateBrowser(request,db,"subject");assert(session.sessionId);db.raw.close();});
