import test from "node:test";
import assert from "node:assert/strict";
import {sqlStore} from "./sql_store.mjs";
import {startLogin,finishLogin,digest,authenticateBrowser} from "../src/browser_sessions.ts";
import {startFlickrOAuth,completeFlickrOAuth,retireOAuthSlot,observeStagedSlot} from "../src/flickr_oauth.ts";
async function fixture(){const db=sqlStore();const login=await startLogin(db);const cookie=await finishLogin(db,{stateDigest:digest(login.state),nonceDigest:digest(login.nonce),googleSub:"subject",ownerSub:"subject"});const session=await authenticateBrowser(new Request("https://flickrgroupaddr.com/",{headers:{Cookie:cookie.split(";")[0]}}),db,"subject");db.raw.prepare("INSERT INTO flickr_links VALUES(?,'owner',1,'paused')").run(session.userId);db.raw.prepare("INSERT INTO flickr_connection_state(user_id,state,local_state) VALUES(?,'unlinked','absent')").run(session.userId);db.raw.prepare("INSERT INTO flickr_write_gates VALUES('user',?,0,1),('deployment','*',0,1)").run(session.userId);
 const values=Array(5).fill(""),callbacks=[];let grant="",requests=0,exchanges=0,owner="owner";
 const slots={read:async i=>values[i],writer:i=>({replace:async value=>{values[i]=value;}})},writer={replace:async value=>{grant=value;}};
 const secrets={FLICKR_APPLICATION:{get:async()=>JSON.stringify({schemaVersion:1,consumerKey:"app",consumerSecret:"secret"})},FLICKR_GRANT:{get:async()=>grant}};
 const fetcher=async request=>{const url=new URL(request.url);const header=Object.fromEntries([...request.headers.get("Authorization").matchAll(/(oauth_[a-z_]+)="([^"]*)"/g)].map(x=>[x[1],decodeURIComponent(x[2])]));if(url.pathname.endsWith("request_token")){assert.equal(await request.text(),"");requests++;callbacks.push(new URL(header.oauth_callback));return new Response(`oauth_callback_confirmed=true&oauth_token=temp-${requests}&oauth_token_secret=temp-secret`);}if(url.pathname.endsWith("access_token")){assert.equal(await request.text(),"");assert.equal(header.oauth_verifier,"verifier");exchanges++;return new Response("oauth_token=active-token&oauth_token_secret=active-secret");}assert.equal(url.searchParams.get("method"),"flickr.auth.oauth.checkToken");return Response.json({stat:"ok",oauth:{token:{_content:"active-token"},perms:{_content:"write"},user:{nsid:owner}}});};return {db,session,slots,writer,secrets,fetcher,callbacks,counts:()=>({requests,exchanges}),wrongOwner:()=>owner="other"};}
test("OAuth callback activates verified native generation once and retires temporary slot",async()=>{const f=await fixture();const result=await startFlickrOAuth(f.db,f.session,1,f.secrets,f.slots,f.fetcher);assert.equal(result.schemaVersion,1);const token=new URL(result.authorizationUrl).searchParams.get("oauth_token"),state=f.callbacks[0].searchParams.get("state");assert.equal(await completeFlickrOAuth(f.db,state,token,"verifier",f.secrets,f.slots,f.writer,f.fetcher),true);assert.equal(await completeFlickrOAuth(f.db,state,token,"verifier",f.secrets,f.slots,f.writer,f.fetcher),false);assert.equal(f.counts().exchanges,1);assert.equal(f.db.raw.prepare("SELECT state FROM flickr_links").get().state,"linked");assert.equal(await retireOAuthSlot(f.db,result.authorizationTransactionId,f.slots),true);assert.equal(f.db.raw.prepare("SELECT phase FROM flickr_oauth_transactions").get().phase,"retired");const rows=JSON.stringify(f.db.raw.prepare("SELECT * FROM flickr_oauth_transactions").all());assert(!rows.includes("temp-secret"));assert(!rows.includes("active-secret"));f.db.raw.close();});
test("five live native OAuth slots bound creation before request-token calls",async()=>{const f=await fixture();for(let i=0;i<5;i++)await startFlickrOAuth(f.db,f.session,1,f.secrets,f.slots,f.fetcher);await assert.rejects(startFlickrOAuth(f.db,f.session,1,f.secrets,f.slots,f.fetcher));assert.equal(f.counts().requests,5);assert.equal(f.db.raw.prepare("SELECT COUNT(*) n FROM flickr_oauth_transactions").get().n,5);f.db.raw.close();});
test("wrong verified Flickr owner never changes old connection authority",async()=>{const f=await fixture();const result=await startFlickrOAuth(f.db,f.session,1,f.secrets,f.slots,f.fetcher);f.wrongOwner();assert.equal(await completeFlickrOAuth(f.db,f.callbacks[0].searchParams.get("state"),new URL(result.authorizationUrl).searchParams.get("oauth_token"),"verifier",f.secrets,f.slots,f.writer,f.fetcher),false);assert.equal(f.db.raw.prepare("SELECT link_revision FROM flickr_links").get().link_revision,1);assert.equal(f.db.raw.prepare("SELECT COUNT(*) n FROM flickr_lifecycle_operations").get().n,0);f.db.raw.close();});

test("native staging waits for the exact schema generation transaction and pair",async()=>{const expected={schemaVersion:1,generation:"g",transactionId:"tx",token:"t",tokenSecret:"s"};let reads=0;await observeStagedSlot(async()=>JSON.stringify(++reads<3?{...expected,generation:"old"}:expected),expected,async()=>{});assert.equal(reads,3);for(const changed of [{schemaVersion:2},{generation:"other"},{transactionId:"other"},{token:"other"},{tokenSecret:"other"},{extra:true}]){let count=0;await assert.rejects(observeStagedSlot(async()=>{count++;return JSON.stringify({...expected,...changed});},expected,async()=>{}),/native_staging_unconfirmed/);assert.equal(count,16);}});
