// Node imports the executable TypeScript registry; Python owns artifact writing/checking.
import { ROUTES, GUARDS, ERROR_SCHEMA } from "../src/registry.ts";
const paths={};
for(const route of ROUTES){
 const method=route.method.toLowerCase();if(paths[route.pathPattern]?.[method])throw new Error("Duplicate route");
 const noStore={description:"Always no-store",schema:{type:"string",const:"no-store"}};
 const responses={};
 for(const status of route.successStatuses)responses[status]={description:route.handler==="admin"?"Administrative operation result":route.handler==="current"?"Current installation":route.handler==="binding"?"Fresh verified photo binding":"Complete ordered admission snapshot",headers:{"Cache-Control":noStore},...(status===204?{}:{content:{"application/json":{schema:route.response}}})};
 for(const status of route.handler==="current"?[400,401,405,503]:[400,401,403,405,409,413,415,422,503])responses[status]={description:status===401&&route.auth!=="browser_session"?"Missing authentication has an empty body and bare Bearer challenge; invalid credentials return the error representation.":"Request rejected",headers:{"Cache-Control":noStore,...(route.auth!=="browser_session"&&[400,401,403].includes(status)?{"WWW-Authenticate":{description:"Present for authentication-envelope and insufficient-scope errors; not for application validation errors.",schema:{type:"string"}}}:{}),...(status===405?{Allow:{schema:{type:"string",const:route.method}}}:{})},content:{"application/json":{schema:ERROR_SCHEMA}}};
 responses[400].description="Application errors use JSON/no-store. ADR 0054 permits the bounded early provider duplicate-Authorization rejection to use non-JSON HTTP 400 without application headers; it cannot redirect, set session cookies, expose application data or serve the shell.";
 responses[400].content["text/html"]={schema:{type:"string"}};
 const description=route.handler==="admin"?"Authenticated private browser session. Unsafe operations require exact Origin and session CSRF; sensitive operations require recent Google authentication.":route.handler==="current"?"No query parameters or request body. Pending credentials authorize only this safe read.":route.handler==="binding"?"Current plug-in credential only. Verifies exact owner/public photo using the current native grant; commits a stable binding only under unchanged authority.":"Current plug-in credential only. One complete selection, one D1 transaction and at most one post-commit wake. No Flickr call occurs in this request. Expired proof is acceptable only when every pair already exists.";
 (paths[route.pathPattern]??={})[method]={operationId:route.id,description,security:[route.auth==="browser_session"?{browserSessionCookie:[]}:{installationBearer:[]}],...(route.request?{requestBody:{required:true,content:{"application/json":{schema:route.request}}}}:{}),responses};
}
console.log(JSON.stringify({inventory:{schemaVersion:1,scope:"installation-read-and-photo-admission",routes:ROUTES,guards:GUARDS,proofEndpointsExcluded:true},openapi:{openapi:"3.2.0",info:{title:"FGA API backend",version:"0.0.0"},paths,components:{securitySchemes:{installationBearer:{type:"http",scheme:"bearer"},browserSessionCookie:{type:"apiKey",in:"cookie",name:"__Host-fga_admin"}}}}}));
