// Local visual/interaction review of production assets using simulated API data only.
import http from "node:http";
import {readFile,writeFile} from "node:fs/promises";
const root=new URL("../assets/admin/",import.meta.url),now=new Date().toISOString().replace("Z","000Z");
let connection={schemaVersion:1,revision:7,state:"linked",flickrOwnerNsid:"123456789@N00",verifiedPermission:"write",verifiedAt:now,localCredentialState:"available",fgaOperationState:"read_only",flickrPermissionState:"not_requested",userWriteGate:{state:"paused",revision:2},deploymentWriteGate:{state:"paused",revision:3}};
const session={schemaVersion:1,sessionId:"example-session",revision:1,sessionSetRevision:1,createdAt:now,recentAuthenticationAt:now,lastActivityAt:now,expiresAt:now,csrfToken:"A".repeat(43)};
const codes=[];let counter=0;
const detail=(id,label="Lightroom workstation")=>({schemaVersion:1,pluginCodeId:id,installationLabel:label,state:"active",revision:1,createdAt:now,revokedAt:null,lastAuthenticatedAt:null,rotationDueAt:"2027-09-13T00:00:00.000000Z",currentVersion:{versionId:id+"-v1",state:"current",createdAt:now,expiresAt:null},pendingCandidate:null,lastLifecycleOutcome:{kind:"created",versionId:id+"-v1",occurredAt:now}});
codes.push(detail("preview-installation"));
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,"http://localhost"),reply=(status,value,type="application/json")=>{res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"});res.end(type==="application/json"?JSON.stringify(value):value);};try{
 if(req.method==="GET"&&url.pathname==="/admin/"){let html=await readFile(new URL("index.html",root),"utf8");html=html.replace('<main>','<main><div class="preview"><strong>Local UI review · simulated data and actions. No account changes.</strong></div>');return reply(200,html,"text/html; charset=utf-8");}
 const asset={"/admin/app.mjs":"app.mjs","/admin/model.mjs":"model.mjs","/admin/styles.css":"styles.css","/admin/plugin-codes-ui.mjs":"plugin-codes-ui.mjs","/admin/plugin-code-transfer.mjs":"plugin-code-transfer.mjs","/admin/submission-status-ui.mjs":"submission-status-ui.mjs","/admin/submission-status-model.mjs":"submission-status-model.mjs"}[url.pathname];if(req.method==="GET"&&asset)return reply(200,await readFile(new URL(asset,root),"utf8"),asset.endsWith(".css")?"text/css":"text/javascript");
 if(req.method==="GET"&&url.pathname==="/api/v001/admin/session")return reply(200,{...session,recentAuthenticationAt:new Date().toISOString().replace("Z","000Z")});
 if(req.method==="GET"&&url.pathname==="/api/v001/admin/flickr-connection")return reply(200,connection);
 if(req.method==="GET"&&url.pathname==="/api/v001/admin/sessions")return reply(200,{schemaVersion:1,sessionSetRevision:1,sessions:[{...session,csrfToken:undefined,sessionSetRevision:undefined,isCurrent:true,state:"active",revokedAt:null}],nextPageToken:null});
 if(req.method==="GET"&&url.pathname==="/api/v001/admin/group-submission-intents"){
  const observedAt=new Date().toISOString().replace("Z","000Z"),view=url.searchParams.get("view")??"active";
  const base={fgaPhotoBindingId:"preview-binding",flickrPhotoId:"preview-photo",flickrGroupId:"preview-group",groupDisplayName:"Example Flickr group",groupDisplayNameObservedAt:now,stateRevision:1,createdAt:now,stateChangedAt:now,attemptCount:1};
  const protectedRow={...base,fgaSubmissionIntentId:"preview-protected",state:"moderation_submitted",terminalAt:now,queue:null,lastOutcome:{reasonCode:"moderation_submission_recorded",flickrResultCode:6,observedAt:now,correlationId:"preview-attempt"},permanentSubmissionBlock:{reasonCode:"moderation_submission_recorded",createdAt:now},attention:null};
  const activeRow={...base,fgaSubmissionIntentId:"preview-active",state:"queued",terminalAt:null,queue:{isPartitionHead:true,activeAheadInPartition:0,nextWorkNotBefore:now,holds:[]},lastOutcome:null,permanentSubmissionBlock:null,attention:null};
  return reply(200,{schemaVersion:1,observedAt,view,pageSize:50,photoBindingId:null,summary:{activeIntentCount:1,activePartitionCount:1,attentionIntentCount:0,oldestActiveEnqueuedAt:now,writeGates:[]},intents:view==="attention"?[]:view==="history"?[activeRow,protectedRow]:[activeRow],nextPage:null,recommendedPollAfterSeconds:15});
 }
 if(req.method==="GET"&&url.pathname==="/api/v001/plugin-codes")return reply(200,{schemaVersion:1,pluginCodes:codes});
 if(req.method==="GET"&&url.pathname.startsWith("/api/v001/plugin-codes/")){const row=codes.find(x=>x.pluginCodeId===url.pathname.split("/").at(-1));if(!row)return reply(404,{error:{code:"not_found"}});res.setHeader("ETag",`"pc:${row.pluginCodeId}:${row.revision}"`);return reply(200,row);}
 if(req.method==="PATCH"&&url.pathname.startsWith("/api/v001/plugin-codes/")){let body="";for await(const chunk of req){body+=chunk;if(body.length>16384)return reply(413,{error:{code:"too_large"}});}const input=JSON.parse(body),parts=url.pathname.split("/"),row=codes.find(x=>x.pluginCodeId===parts[4]);if(!row)return reply(404,{error:{code:"not_found"}});if(req.headers["if-match"]!==`"pc:${row.pluginCodeId}:${row.revision}"`)return reply(412,{error:{code:"precondition_failed"}});let kind="revoked",versionId=null;if(parts.includes("rotation-candidates")){versionId=row.pendingCandidate?.versionId;if(!versionId||versionId!==parts.at(-1))return reply(409,{error:{code:"rotation_conflict"}});if(input.state==="current"){row.currentVersion={...row.pendingCandidate,state:"current",expiresAt:null};kind="rotation_completed";}else kind="rotation_cancelled";row.pendingCandidate=null;}else{row.state="revoked";row.currentVersion=null;row.pendingCandidate=null;row.revokedAt=new Date().toISOString().replace("Z","000Z");}row.revision++;row.lastLifecycleOutcome={kind,versionId,occurredAt:new Date().toISOString().replace("Z","000Z")};res.setHeader("ETag",`"pc:${row.pluginCodeId}:${row.revision}"`);return reply(200,row);}
 if(req.method==="POST"){let size=0,body="";for await(const chunk of req){size+=chunk.length;if(size>16384)return reply(413,{error:{message:"Preview request too large"}});body+=chunk;}const input=body?JSON.parse(body):{};
  if(url.pathname==="/api/v001/plugin-codes"){const row=detail("preview-created-"+(++counter),input.installationLabel);codes.push(row);return reply(201,{schemaVersion:1,pluginCodeId:row.pluginCodeId,pluginCode:Array(13).fill("0000").join("-")});}
  if(url.pathname.endsWith("/rotation-candidates")){const row=codes.find(x=>x.pluginCodeId===url.pathname.split("/").at(-2));if(!row)return reply(404,{error:{code:"not_found"}});const candidate=row.pluginCodeId+"-candidate";row.pendingCandidate={versionId:candidate,state:"pending_rotation",createdAt:now,expiresAt:new Date(Date.now()+900000).toISOString().replace("Z","000Z")};row.revision++;return reply(201,{schemaVersion:1,pluginCodeId:row.pluginCodeId,rotationCandidateId:candidate,expiresAt:row.pendingCandidate.expiresAt,pluginCode:Array(13).fill("0000").join("-")});}
  if(url.pathname.endsWith("/authorization")||url.pathname.endsWith("/reauthentication"))return reply(503,{error:{code:"preview_only",message:"External sign-in is disabled in this synthetic UI review."}});
  if(url.pathname.endsWith("/disconnection")){if(input.expectedFlickrOwnerNsid!==connection.flickrOwnerNsid)return reply(400,{error:{message:"Owner confirmation mismatch"}});connection={...connection,revision:connection.revision+1,state:"disconnected",localCredentialState:"retired",fgaOperationState:"stopped",verifiedPermission:null,verifiedAt:null,flickrPermissionState:"owner_action_required",userWriteGate:{state:"paused",revision:3}};return reply(200,connection);}
  if(url.pathname.endsWith("/resume")){const key=url.pathname.includes("/deployment/")?"deploymentWriteGate":"userWriteGate";connection[key]={state:"enabled",revision:connection[key].revision+1};connection.fgaOperationState=connection.userWriteGate.state==="enabled"&&connection.deploymentWriteGate.state==="enabled"?"enabled":"read_only";return reply(200,connection);}
  if(url.pathname.endsWith("/logout")){res.writeHead(204,{"Cache-Control":"no-store"});return res.end();}
 }
 if(url.pathname==="/admin/signed-out")return reply(200,"<h1>Signed out of the simulated review session</h1>","text/html");
 return reply(404,{error:{message:"Preview route unavailable"}});
 }catch{return reply(500,{error:{message:"Preview unavailable"}});}});
server.listen(0,"127.0.0.1",async()=>{await writeFile(new URL("../.coordination-runs/admin-ui-review.json",import.meta.url),JSON.stringify({url:"http://127.0.0.1:"+server.address().port+"/admin/",pid:process.pid,synthetic:true}));});
